COMBO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes

# Size optimisations
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
MOUSEKEY_ENABLE = no
MAGIC_ENABLE = no
INTROSPECTION_KEYMAP_C = combos.c
LTO_ENABLE = yes
CONVERT_TO = blok